### ISSUE TITLE
Template XONTRIBS_AUTOLOAD_DISABLED conflict with other xontribs and type conflicts

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xontrib-template#18]
The template suggests disabling autoloading via
`$XONTRIBS_AUTOLOAD_DISABLED = {"ptk_shell", }`

There are a few of issues with this:

- It would override the same variable set by other xontribs instead of appending
- From the docs, the type of `XONTRIBS_AUTOLOAD_DISABLED` could either by a bool or a list, but you use a set, so actually appending this variable becomes a challenge due to a difference in updating lists and sets
- `ptk_shell` should be replaced with a template variable to put the xontrib name there `{{project_package_name}}`?

**Comment by jnoortheen** [comment]
Closing as the PR is merged already.

**Comment by eugenesvk** [comment]
The PR only addresses the last point, not the first two

**Comment by jnoortheen** [comment]
Now the readme is updated
