### ISSUE TITLE
Idea: $RANDOM

### ISSUE THREAD

**Issue by ksaj** [xonsh/xontrib-template#37]
Hello! I have an idea!

Under bash, zsh, and probably others, if you type "echo $RANDOM" you get a random number. It is a different random number each time it is echoed.

I thought this should be a thing in Xonsh because this post from It's FOSS on Mastodon treats it as a given that "echo $RANDOM" on the (unnamed) CLI will have this effect, but this is not the case for Xonsh.

https://infosec.exchange/deck/@itsfoss@mastodon.social/111277379265186528

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by AstraLuma** [comment]
Xonsh is not a bourne-ish shell. You want `@(random.random())`.
