### ISSUE TITLE
Copier is not working

### ISSUE THREAD

**Issue by anki-code** [xonsh/xontrib-template#41]
Hey @jnoortheen !

I tried to run copier to create xontrib but got an error. It looks that current instructions is not working.

```xsh
docker run -it --rm -v $PWD:/ddd python:3.9-alpine sh
pip install copier jinja2-time cookiecutter
copier gh:xonsh/xontrib-template .
# Unknown sub-command 'gh:xonsh/xontrib-template'
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
seems the CLI is now updated https://copier.readthedocs.io/en/stable/changelog/#v800-2023-06-04

**Comment by jnoortheen** [comment]
Fixed in https://github.com/xonsh/xontrib-template/commit/d963ad5aeffc9c290011077819acd50f9765bdd6
